# Generated by Django 4.2.4 on 2023-10-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('barrio', models.CharField(max_length=30)),
                ('titulos', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad_equipos', models.IntegerField()),
                ('premio', models.CharField(max_length=30)),
                ('fecha_comienzo', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='torneos')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=2)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='jugadores')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProFi.equipo')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ManyToManyField(blank=True, to='AppProFi.torneo'),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('titulos', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entrenadores')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProFi.equipo')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
