# Generated by Django 4.2.4 on 2023-09-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProFi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='torneo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ManyToManyField(blank=True, to='AppProFi.torneo'),
        ),
    ]
